#!/usr/bin/env bash
set -xeuo pipefail

NAME="hello"

AWS_REGION="us-east-1"

ECR_URL="055097670573.dkr.ecr.us-east-1.amazonaws.com"
ECR_REPO="snowflake-external-function-poc"

IMAGE_TAG="snowflake-external-function-poc"
IMAGE_VERSION="latest"

FUNCTION_NAME="snowflake-external-function-poc-docker"

export AWS_PAGER=""

# Build container image, tag, & push to ECR
aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$ECR_URL"
docker build -t "$IMAGE_TAG" ..
docker tag "$IMAGE_TAG:$IMAGE_VERSION" "$ECR_URL/$IMAGE_TAG:$IMAGE_VERSION"
docker push "$ECR_URL/$IMAGE_TAG:$IMAGE_VERSION"

# Update Lambda code
LATEST_SHA=$(aws ecr describe-images --output json --repository-name "$ECR_REPO" --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageDigest' | jq . --raw-output)
aws lambda update-function-code --function-name "$FUNCTION_NAME" --image-uri "$ECR_URL/$IMAGE_TAG@$LATEST_SHA"
aws lambda wait function-updated-v2 --function-name "$FUNCTION_NAME"

# Update Lambda configuration
aws lambda update-function-configuration --function-name "$FUNCTION_NAME" --cli-input-json "file://../ox/$NAME/lambda_function.json"
aws lambda wait function-updated-v2 --function-name "$FUNCTION_NAME"

# Update Snowflake function signature
/Applications/SnowSQL.app/Contents/MacOS/snowsql -f "../ox/$NAME/external_function.sql"
